export const books = [
    {
        id: 1,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        publication_date: "July 11, 1960",
        genre: "Classic Fiction",
    },
    {
        id: 2,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        publication_date: "April 10, 1925",
        genre: "Classic Fiction",
    },
    {
        id: 3,
        title: "1984",
        author: "George Orwell",
        publication_date: "June 8, 1949",
        genre: "Dystopian Fiction",
    },
    {
        id: 4,
        title: "The Hunger Games",
        author: "Suzanne Collins",
        publication_date: "September 14, 2008",
        genre: "Young Adult Fiction",
    },
    {
        id: 5,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        publication_date: "January 28, 1813",
        genre: "Classic Fiction",
    },
    {
        id: 6,
        title: "To the Lighthouse",
        author: "Virginia Woolf",
        publication_date: "May 5, 1927",
        genre: "Modernist Fiction",
    },
    {
        id: 7,
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        publication_date: "July 16, 1951",
        genre: "Coming-of-age Fiction",
    },
    {
        id: 8,
        title: "The Lord of the Rings",
        author: "J.R.R. Tolkien",
        publication_date: "July 29, 1954",
        genre: "Fantasy Fiction",
    },
    {
        id: 9,
        title: "The Chronicles of Narnia",
        author: "C.S. Lewis",
        publication_date: "October 16, 1950",
        genre: "Fantasy Fiction",
    },
    {
        id: 10,
        title: "The Picture of Dorian Gray",
        author: "Oscar Wilde",
        publication_date: "June 20, 1890",
        genre: "Gothic Fiction",
    },
    {
        id: 11,
        title: "Harry Potter and the Philosopher's Stone",
        author: "J.K. Rowling",
        publication_date: "June 26, 1997",
        genre: "Fantasy Fiction",
    },
    {
        id: 12,
        title: "The Color Purple",
        author: "Alice Walker",
        publication_date: "April 1982",
        genre: "Epistolary Fiction",
    },
    {
        id: 13,
        title: "The Handmaid's Tale",
        author: "Margaret Atwood",
        publication_date: "1985",
        genre: "Dystopian Fiction",
    },
    {
        id: 14,
        title: "The Alchemist",
        author: "Paulo Coelho",
        publication_date: "1988",
        genre: "Fable",
    },
    {
        id: 15,
        title: "The Kite Runner",
        author: "Khaled Hosseini",
        publication_date: "May 29, 2003",
        genre: "Historical Fiction",
    },
];
